update

diff --git a/common/install/install-composer b/common/install/install-composer
--- a/common/install/install-composer
+++ b/common/install/install-composer
@@ -1,20 +1,24 @@
 #!/bin/bash
 
-mkdir -p ~/Downloads && cd $_
+if [[ "$(isinstalled git)" == "no" ]]; then
+    mkdir -p ~/Downloads && cd $_
 
-EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
-php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+    EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
+    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+    ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
 
-if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
-then
-    >&2 echo 'ERROR: Invalid installer checksum'
+    if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
+    then
+        >&2 echo 'ERROR: Invalid installer checksum'
+        rm composer-setup.php
+        exit 1
+    fi
+
+    php composer-setup.php --quiet
+    RESULT=$?
     rm composer-setup.php
-    exit 1
+    sudo mv composer.phar /usr/local/bin/composer
+    exit $RESULT
+else
+    composer --version
 fi
-
-php composer-setup.php --quiet
-RESULT=$?
-rm composer-setup.php
-sudo mv composer.phar /usr/local/bin/composer
-exit $RESULT
