update

diff --git a/install/install-base b/install/install-base
--- a/install/install-base
+++ b/install/install-base
@@ -7,17 +7,30 @@ colors="https://raw.githubusercontent.com/barabasz/bin/main/lib/colors.sh"
 printf="https://raw.githubusercontent.com/barabasz/bin/main/lib/print.sh"
 github="https://raw.githubusercontent.com/barabasz/bin/main/install"
 
-# loading variables and functions
-source <(curl -fsSL $varbls) && echo "Variables loaded." || { echo "Error loading variables."; return 1; }
-source <(curl -fsSL $fnfile) && echo "Functions loaded." || { echo "Error loading functions."; return 1; }
-source <(curl -fsSL $colors) && echo "Colors loaded." || { echo "Error loading colors lib."; return 1; }
-source <(curl -fsSL $printf) && echo "Print loaded." || { echo "Error loading print lib."; return 1; }
+# loading variables and functions (using wget for compatibility)
+source <(wget -q -O - $varbls) && echo "Variables loaded." || { echo "Error loading variables."; return 1; }
+source <(wget -q -O - $fnfile) && echo "Functions loaded." || { echo "Error loading functions."; return 1; }
+source <(wget -q -O - $colors) && echo "Colors loaded." || { echo "Error loading colors lib."; return 1; }
+source <(wget -q -O - $printf) && echo "Print loaded." || { echo "Error loading print lib."; return 1; }
 
-printf "\n\n-------------------------------\n"
-printf "${redbi}System base installation script${clear}"
-printf "\n-------------------------------\n\n"
+printtitle 'Installation of base system components'
 
-# forcing sudo password
+# installing sudo & culr if not installed (Linux)
+if [[ "$(osname)" != "macos" ]]; then
+    if [[ $(isinstalled "sudo") -eq 0 ]]; then
+        printhead 'Installing sudo...'
+        su -c "apt-get install -qq sudo"
+        su -c "echo 'ALL ALL=(ALL:ALL) ALL' | sudo EDITOR='tee -a' visudo"
+        verinfo "sudo"
+    fi
+    if [[ $(isinstalled "curl") -eq 0 ]]; then
+        printhead 'Installing curl...'
+        aptinstall "curl"
+        verinfo "curl"
+    fi
+fi
+
+# forcing sudo password for the rest of the script
 sudo echo > /dev/null
 
 # create base directories
diff --git a/install/install-brew b/install/install-brew
--- a/install/install-brew
+++ b/install/install-brew
@@ -1,11 +1,8 @@
 #!/bin/zsh
 
-# load functions
-if [[ -f $ZDOTDIR/.zsh_functions ]]; then
-    source $ZDOTDIR/.zsh_functions
-else
-    source <(curl -fsSL "$MYGH/config/main/zsh/.zsh_functions")
-fi
+# load variables and functions
+zlf=$ZSH_LOAD_FILE; err="$0: unable to load ZSH_LOAD_FILE"
+[[ -f $zlf ]] && source $zlf || { printf "$err\n";  exit 1 }
 
 export HOMEBREW_NO_ENV_HINTS=1
 export HOMEBREW_NO_EMOJI=1
diff --git a/install/install-mc b/install/install-mc
--- a/install/install-mc
+++ b/install/install-mc
@@ -1,22 +1,27 @@
-#!/bin/bash
+#!/bin/zsh
 
 # mc (Midnight Commander)
 # feature rich full-screen text mode visual file manager
 # https://midnight-commander.org/
+
+# load variables and functions
+zlf=$ZSH_LOAD_FILE; err="$0: unable to load ZSH_LOAD_FILE"
+[[ -f $zlf ]] && source $zlf || { printf "$err\n";  exit 1 }
 
 appname='Midnight Commander'
 cliname=mc
 dirname=$cliname
 pkgname=midnight-commander
 
-if [[ ! $(isinstalled $cliname) ]]; then
+if [[ $(isinstalled $cliname) == 0 ]]; then
+echo "Installing $appname..."
     if [[ "$(osname)" == "macos" ]]; then
         brew install -q $pkgname
     else
         aptinstall $cliname
     fi
 else
-    verinf $cliname "$appname"
+    verinfo $cliname "$appname"
 fi
 
 makeconfln $dirname
